create sequence if not exists hibernate_sequence start with 1 increment by 1;

create table if not exists accounts (
	id bigint generated by default as identity(start with 1, increment by 1) primary key,
	username varchar(100) not null,
	encrypted_password varchar(100) not null,
	constraint uk_accounts_username unique (username)
);

create table if not exists links (
	id bigint generated by default as identity(start with 1, increment by 1) primary key,
	url varchar(2000) not null,
	key varchar(10) not null,
	account_id bigint not null,
	redirect_code int default 302 not null,
	visit_count int  default 0 not null,
	constraint fk_account_id_accounts foreign key (account_id) references accounts(id),
	constraint uk_links_key unique (key),
	constraint uk_url_account_id unique (url, account_id)
);
